### ISSUE TITLE
mutate_derivative and mutate_integral docstrings state erroneous requirements of sensor_data

### ISSUE THREAD

**Issue by itismeghasyam** [Sage-Bionetworks/mhealthtools#116]
The input `sensor_data` we are asking for mutate_derivative and mutate_integral, has a `t` column according to the docstring. 

If we do not supply the `sampling_rate` (it is a compulsory parameter now), we can still compute the sampling rate from `sensor_data$t` 

So maybe the `sampling_rate` parameter can be made an optional one

**Comment by philerooski** [comment]
The docstring is incorrect. `sensor_data` should only require columns `col` (one of the passed variables).

I believe `sampling_rate` is included as a parameter because we were always computing `sampling_rate` in the sensor-level wrappers, so there was no need to compute it more than once. But computing sampling rate in the wrappers isn't necessary in the current implementation. It only needs to be computed if the user specifies one or more of `frequency_filter`, `derived_kinematics = T`, or they are using one of our included feature extraction functions.

Whether we swap out the `sampling_rate` requirement for a `sensor_data` having a `t` column requirement comes down to whichever is more general. What if a user wants to take a derivative after windowing the data? This is exactly what we do when `derived_kinematics = T` and the data has been windowed.
