### ISSUE TITLE
get_walk_features.R bugs/improvements

### ISSUE THREAD

**Issue by th1vairam** [Sage-Bionetworks/mhealthtools#86]
Following use cases should be supported.

walk_features = get_walk_features(accelerometer_data, gyroscope_data = NULL, fun = list(frequency_domain_summary, time_domain_summary))

or 

walk_features = get_walk_features(accelerometer_data = NULL, fun = list(frequency_domain_summary, time_domain_summary))

**Comment by th1vairam** [comment]
models function should only take acceleration and gyroscope raw data and not the derived functionalities like IMF, jerk, acceleration, velocity, displacement and outputs features, etc...

**Comment by th1vairam** [comment]
Why there is n't any error column returned?

**Comment by philerooski** [comment]
```
walk_features = get_walk_features(accelerometer_data, gyroscope_data = NULL, fun = list(frequency_domain_summary, time_domain_summary))
```
This wouldn't quite work because `frequency_domain_summary` and ` time_domain_summary` require other arguments in addition to a numeric vector. You would need to wrap them in closures, and those vary from function to function. See https://github.com/Sage-Bionetworks/mhealthtools/blob/master/R/sensors.R#L152

```
walk_features = get_walk_features(accelerometer_data = NULL, fun = list(frequency_domain_summary, time_domain_summary))
```
What do you expect as output when you don't pass any data to a feature extraction function?

> Why there is n't any error column returned?

Is this a separate issue?

**Comment by philerooski** [comment]
Oh.... I typed all of that and realized what you probably meant to file an issue about was the ability to omit either accelerometer or gyroscope data. Is this correct?

**Comment by th1vairam** [comment]
frequency_range = NULL should be the default and that should correspond to no bandpass filtering.

**Comment by th1vairam** [comment]
After looking at the use cases, it looks like we might need the transform = T/F option needed and exposed in the module level.

**Comment by th1vairam** [comment]
time_range  = NULL should be the default, which corresponds to no filtering of the original signal using all the data.

**Comment by philerooski** [comment]
`transform = F` is equivalent to `transform = function(x) x` (identity). Whether or not to expose the transform parameter at the assay level is another question.

Right now one of the few advantages of using the assay level functions is that they take care of the transform/transformation for you.

**Comment by th1vairam** [comment]
Agreed. However, not everyone wants to do the transformation. In fact, most of them will not need transformation because of the enormous number of features generated. So, we should have the default as no transformation.

**Comment by philerooski** [comment]
Closing this issue because it's been split into the three issues above. If you have comments on something that's already been mentioned, please make it in the relevant issue. If it's something completely new related to the functionality of the assay level functions, feel free to comment here or (even better) open a new issue.
